import { Document, Font, Page, StyleSheet } from '@react-pdf/renderer';
import Html from 'react-pdf-html';
import PrivacyComponent from './login/PrivacyComponent';
import { renderToString } from 'react-dom/server';
import { useEffect } from 'react';

Font.register({
  family: 'Roboto',
  fonts: [
    {
      src: '/fonts/Roboto-Regular.ttf',
      fontWeight: 'normal',
    },
    {
      src: '/fonts/Roboto-Medium.ttf',
      fontWeight: 'bold',
    },
  ],
});

const styles = StyleSheet.create({
  page: {
    padding: '30px',
    fontSize: '12px',
    // paddingBottom: '80pt',
    display: 'flex',
    flexDirection: 'row',
  },
});
// let htmlString = renderToString(<PrivacyComponent />);
let htmlString = `
<html>
<head>
  <meta charset="utf-8" />
  <title>Email Preview</title>
  <style>
    body {
      font-family: 'Roboto', Arial, sans-serif;
      background-color: #ffffff;
      margin: 0;
      padding: 0;
      padding-top: 10px;
      overflow: auto;
    }
    .email-container {
      max-width: 600px;
      width: 100%;
      margin: 0 auto;
      border-collapse: collapse;
      overflow: hidden;
      #box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
      padding-bottom: 20px;
    }
    

    p {
      font-size: 14px;
      line-height: 1.5;
      color: #333;
    }

  </style>
</head>
<body>
  <div class="email-container">
  <p>
            <b>Terms of Use</b>
            <br />
            Last updated: 16 March 2024
            <br />
            Metric Media Pte Ltd ("us", "we", or "our") operates the Amoro.AI
            software (hereinafter referred to as the "Service").
            <br />
            <b>1. Introduction</b>
            <br />
            This Terms of Use agreement (the "Agreement") governs your use of
            the Service. By accessing or using the Service, you agree to be
            bound by this Agreement.
            <br />
            <b>2. Use of the Service</b>
            <br />
            2.1. You must be at least 18 years old to access and use the
            Service.
            <br />
            2.2. You are responsible for maintaining the confidentiality of your
            account credentials and for all activities that occur under your
            account.
            <br />
            2.3. You agree not to use the Service for any unlawful or
            unauthorized purpose, including but not limited to violating any
            applicable laws or regulations.
            <br />
            <b>3. User Responsibility for Content</b>
            <br />
            3.1. Users of the Service are solely responsible for the content
            they create or generate using the Amoro.AI software ("Content"). As
            Amoro.AI is a language model that writes content based on user
            input, users must ensure that all Content adheres to applicable
            compliance, legal, and regulatory obligations.
            <br />
            3.2. While using the Service, users acknowledge that Amoro.AI may,
            on occasion, generate content that does not fully comply with such
            obligations. Users are expected to conduct proper compliance,
            regulatory, and legal screening of all Content generated by Amoro.AI
            before use.
            <br />
            3.3. Metric Media Pte Ltd and the Amoro.AI software bear no
            responsibility for any breach of compliance, legal, or regulatory
            obligations resulting from the use of the Service or the Content
            generated by Amoro.AI. Users agree to hold Metric Media Pte Ltd
            harmless from any liability arising from such breaches.
            <br />
            <b>4. Intellectual Property Rights</b>
            <br />
            4.1. The Service and its original content, features, and
            functionality are owned by Metric Media Pte Ltd and are protected by
            international copyright, trademark, patent, trade secret, and other
            intellectual property or proprietary rights laws.
            <br />
            4.2. You may not modify, reproduce, distribute, create derivative
            works of, publicly display, publicly perform, republish, download,
            store, or transmit any of the material on the Service, except as
            permitted by these Terms or with the prior written consent of Metric
            Media Pte Ltd.
            <br />
            <b>5. User Content</b>
            <br />
            5.1. You retain ownership of any content you submit, post, or
            display on or through the Service ("User Content"). By submitting,
            posting, or displaying User Content, you grant us a non-exclusive,
            worldwide, royalty-free, sublicensable, and transferable license to
            use, reproduce, distribute, prepare derivative works of, display,
            and perform the User Content in connection with the Service.
            <br />
            5.2. You represent and warrant that you have all rights necessary to
            grant the licenses granted in this section 5 and that your User
            Content does not violate the rights of any third party.
            <br />
            <b>6. Account Usage Restrictions</b>
            <br />
            6.1. Each user account is restricted to one individual user and may
            not be shared with others. User accounts are for personal use only,
            and users may not resell or transfer their account credentials to
            any other individual or entity.
            <br />
            6.2. User accounts are limited to managing the brands specified
            during registration. Unless otherwise approved by Amoro.AI, each
            user account may manage up to two brands.
            <br />
            6.3. Users are permitted to access the Service on up to three
            devices only. Any additional device access may require prior
            approval from Amoro.AI.
            <br />
            <b>7. Disclaimer of Warranties</b>
            <br />
            7.1. The Service is provided "as is" and "as available" without
            warranties of any kind, either express or implied. We disclaim all
            warranties, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, and
            non-infringement.
            <br />
            7.2. We do not warrant that the Service will be uninterrupted,
            secure, or error-free, that defects will be corrected, or that the
            Service or the server that makes it available are free of viruses or
            other harmful components.
            <br />
            7.3. In the event of software downtime, users agree to allow
            Amoro.AI up to 5 working days to rectify the issue. Amoro.AI shall
            have no obligation to provide a refund if the software downtime
            stays within 5 working days from the date of receiving notification
            that the software is down.
            <br />
            <b>8. Limitation of Liability</b>
            <br />
            8.1. In no event shall Metric Media Pte Ltd, its affiliates,
            directors, officers, employees, agents, or licensors be liable for
            any indirect, incidental, special, consequential, or punitive
            damages, including but not limited to loss of profits, data, or
            goodwill, arising from or related to your use of the Service.
            <br />
            <b>9. Governing Law</b>
            <br />
            9.1. These Terms shall be governed by and construed in accordance
            with the laws of [Jurisdiction], without regard to its conflict of
            law principles.
            <br />
            <b>10. Changes to the Terms</b>
            <br />
            10.1. We reserve the right to modify or replace these Terms at any
            time. If a revision is material, we will provide at least 30 days'
            notice prior to any new terms taking effect. What constitutes a
            material change will be determined at our sole discretion.
            <br />
            <b>11. Contact Information</b>
            <br />
            If you have any questions, concerns, or requests regarding these
            Terms, please contact us at:
            <br />
            hello@amoro.ai
            <br />
            <br />
          </p>
  </div>
  
</body>
</html>
`;

// const pageLayout = {
//   tranformSize: ({ size }) => ({ height: size.height - 30, width: size.width + 30 }),
// };

export function PrivacyPdf() {
  return (
    <Document>
      <Page size="A4" style={styles.page} wrap={false}>
        <Html>{htmlString}</Html>
      </Page>
    </Document>
  );
}
